-- MySQL Script generated by MySQL Workbench
-- Sat 03 Jun 2017 01:44:36 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gesane
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gesane` ;

-- -----------------------------------------------------
-- Schema gesane
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gesane` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `gesane` ;

-- -----------------------------------------------------
-- Table `gesane`.`tiposervicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`tiposervicio` ;

CREATE TABLE IF NOT EXISTS `gesane`.`tiposervicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`servicio` ;

CREATE TABLE IF NOT EXISTS `gesane`.`servicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `codigo` VARCHAR(255) NULL,
  `id_tiposervicio` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_servicio_tiposervicio_idx` (`id_tiposervicio` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`tipopago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`tipopago` ;

CREATE TABLE IF NOT EXISTS `gesane`.`tipopago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`sexo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`sexo` ;

CREATE TABLE IF NOT EXISTS `gesane`.`sexo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`tipousuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`tipousuario` ;

CREATE TABLE IF NOT EXISTS `gesane`.`tipousuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`curso` ;

CREATE TABLE IF NOT EXISTS `gesane`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`centro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`centro` ;

CREATE TABLE IF NOT EXISTS `gesane`.`centro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `codigo` VARCHAR(255) NULL,
  `poblacion` VARCHAR(255) NULL,
  `provincia` VARCHAR(255) NULL,
  `telefono` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `direccion` VARCHAR(255) NULL,
  `cod_postal` VARCHAR(255) NULL,
  `pais` VARCHAR(255) NULL,
  `publico` TINYINT(1) NULL,
  `nombresanitario` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`grupo` ;

CREATE TABLE IF NOT EXISTS `gesane`.`grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(255) NULL,
  `id_curso` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_centro` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grupo_curso1_idx` (`id_curso` ASC),
  INDEX `fk_grupo_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_grupo_centro1_idx` (`id_centro` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`usuario` ;

CREATE TABLE IF NOT EXISTS `gesane`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `primer_apellido` VARCHAR(255) NULL,
  `segundo_apellido` VARCHAR(255) NULL,
  `login` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `token` VARCHAR(45) NULL,
  `activo` TINYINT(1) NULL,
  `fecha_alta` DATETIME NULL,
  `validado` TINYINT(1) NULL,
  `id_tipousuario` INT NOT NULL,
  `id_grupo` INT NOT NULL,
  `id_centro` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tipousuario1_idx` (`id_tipousuario` ASC),
  INDEX `fk_usuario_grupo1_idx` (`id_grupo` ASC),
  INDEX `fk_usuario_centro1_idx` (`id_centro` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`paciente` ;

CREATE TABLE IF NOT EXISTS `gesane`.`paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(255) NULL,
  `nombre` VARCHAR(255) NULL,
  `primer_apellido` VARCHAR(255) NULL,
  `segundo_apellido` VARCHAR(255) NULL,
  `direccion` VARCHAR(255) NULL,
  `ciudad` VARCHAR(255) NULL,
  `codigo_postal` VARCHAR(255) NULL,
  `provincia` VARCHAR(255) NULL,
  `pais` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `telefono1` VARCHAR(45) NULL,
  `telefono2` VARCHAR(45) NULL,
  `nombre_padre` VARCHAR(255) NULL,
  `nombre_madre` VARCHAR(255) NULL,
  `fecha_nacimiento` VARCHAR(255) NULL,
  `ciudad_nacimiento` VARCHAR(255) NULL,
  `pais_nacimiento` VARCHAR(255) NULL,
  `sip_aseguradora` VARCHAR(45) NULL,
  `id_tipopago` INT NOT NULL,
  `id_sexo` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_paciente_tipopago1_idx` (`id_tipopago` ASC),
  INDEX `fk_paciente_sexo1_idx` (`id_sexo` ASC),
  INDEX `fk_paciente_usuario1_idx` (`id_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`factura` ;

CREATE TABLE IF NOT EXISTS `gesane`.`factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`tipodependencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`tipodependencia` ;

CREATE TABLE IF NOT EXISTS `gesane`.`tipodependencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`dependencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`dependencia` ;

CREATE TABLE IF NOT EXISTS `gesane`.`dependencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  `id_tipodependencia` INT NOT NULL,
  `id_centro` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dependencia_tipodependencia1_idx` (`id_tipodependencia` ASC),
  INDEX `fk_dependencia_centro1_idx` (`id_centro` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`especialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`especialidad` ;

CREATE TABLE IF NOT EXISTS `gesane`.`especialidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`categoriaprofesional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`categoriaprofesional` ;

CREATE TABLE IF NOT EXISTS `gesane`.`categoriaprofesional` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`medico` ;

CREATE TABLE IF NOT EXISTS `gesane`.`medico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_servicio` INT NULL,
  `id_especialidad` INT NULL,
  `dni` VARCHAR(255) NULL,
  `nombre` VARCHAR(255) NULL,
  `primer_apellido` VARCHAR(255) NULL,
  `segundo_apellido` VARCHAR(255) NULL,
  `fecha_nacimiento` DATETIME NULL,
  `num_colegiado` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `id_categoriaprofesional` INT NOT NULL,
  `id_centro` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medico_servicio1_idx` (`id_servicio` ASC),
  INDEX `fk_medico_especialidad1_idx` (`id_especialidad` ASC),
  INDEX `fk_medico_categoriaprofesional1_idx` (`id_categoriaprofesional` ASC),
  INDEX `fk_medico_centro1_idx` (`id_centro` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`tipoepisodio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`tipoepisodio` ;

CREATE TABLE IF NOT EXISTS `gesane`.`tipoepisodio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`circunstanciasalta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`circunstanciasalta` ;

CREATE TABLE IF NOT EXISTS `gesane`.`circunstanciasalta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`destinoalta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`destinoalta` ;

CREATE TABLE IF NOT EXISTS `gesane`.`destinoalta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`modalidadepisodio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`modalidadepisodio` ;

CREATE TABLE IF NOT EXISTS `gesane`.`modalidadepisodio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`episodio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`episodio` ;

CREATE TABLE IF NOT EXISTS `gesane`.`episodio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_firma` DATETIME NULL,
  `fecha_inicio` DATETIME NULL,
  `fecha_alta` DATETIME NULL,
  `importe` DOUBLE NULL,
  `finalizado` TINYINT(1) NULL,
  `bloqueado` TINYINT(1) NULL,
  `id_servicio` INT NOT NULL,
  `id_paciente` INT NOT NULL,
  `id_factura` INT NOT NULL,
  `id_dependencia` INT NOT NULL,
  `id_medico` INT NOT NULL,
  `id_tipoepisodio` INT NOT NULL,
  `id_episodio` INT NOT NULL,
  `id_circunstanciasalta` INT NOT NULL,
  `id_destinoalta` INT NOT NULL,
  `id_modalidadepisodio` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `motivo_ingreso` LONGTEXT NULL,
  `antecedentes` LONGTEXT NULL,
  `historia_actual` LONGTEXT NULL,
  `exploracion_fisica` LONGTEXT NULL,
  `evolucion_comentarios` LONGTEXT NULL,
  `diagnostico_principal` LONGTEXT NULL,
  `diagnostico_secundarios` LONGTEXT NULL,
  `procedimientos` LONGTEXT NULL,
  `tratamiento_recomendaciones` LONGTEXT NULL,
  `tratamiento_farmacos` LONGTEXT NULL,
  `recomendaciones` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_episodio_servicio1_idx` (`id_servicio` ASC),
  INDEX `fk_episodio_paciente1_idx` (`id_paciente` ASC),
  INDEX `fk_episodio_factura1_idx` (`id_factura` ASC),
  INDEX `fk_episodio_dependencia1_idx` (`id_dependencia` ASC),
  INDEX `fk_episodio_medico1_idx` (`id_medico` ASC),
  INDEX `fk_episodio_tipoepisodio1_idx` (`id_tipoepisodio` ASC),
  INDEX `fk_episodio_episodio1_idx` (`id_episodio` ASC),
  INDEX `fk_episodio_circunstanciasalta1_idx` (`id_circunstanciasalta` ASC),
  INDEX `fk_episodio_destinoalta1_idx` (`id_destinoalta` ASC),
  INDEX `fk_episodio_modalidadepisodio1_idx` (`id_modalidadepisodio` ASC),
  INDEX `fk_episodio_usuario1_idx` (`id_usuario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`medicamento` ;

CREATE TABLE IF NOT EXISTS `gesane`.`medicamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`via`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`via` ;

CREATE TABLE IF NOT EXISTS `gesane`.`via` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`posologia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`posologia` ;

CREATE TABLE IF NOT EXISTS `gesane`.`posologia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`tratamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`tratamiento` ;

CREATE TABLE IF NOT EXISTS `gesane`.`tratamiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  `cuidados` LONGTEXT NULL,
  `importe` DOUBLE NULL,
  `id_medicamento` INT NOT NULL,
  `id_posologia` INT NOT NULL,
  `id_via` INT NOT NULL,
  `id_episodio` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tratamiento_medicamento1_idx` (`id_medicamento` ASC),
  INDEX `fk_tratamiento_posologia1_idx` (`id_posologia` ASC),
  INDEX `fk_tratamiento_via1_idx` (`id_via` ASC),
  INDEX `fk_tratamiento_episodio1_idx` (`id_episodio` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`prueba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`prueba` ;

CREATE TABLE IF NOT EXISTS `gesane`.`prueba` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `informe` LONGTEXT NULL,
  `fecha_peticion` DATETIME NULL,
  `importe` DOUBLE NULL,
  `id_episodio` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prueba_episodio1_idx` (`id_episodio` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`tecnica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`tecnica` ;

CREATE TABLE IF NOT EXISTS `gesane`.`tecnica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`imagen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`imagen` ;

CREATE TABLE IF NOT EXISTS `gesane`.`imagen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `fecha` DATETIME NULL,
  `ubicacion` VARCHAR(255) NULL,
  `id_prueba` INT NOT NULL,
  `id_tecnica` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_imagen_prueba1_idx` (`id_prueba` ASC),
  INDEX `fk_imagen_tecnica1_idx` (`id_tecnica` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`zona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`zona` ;

CREATE TABLE IF NOT EXISTS `gesane`.`zona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`zonaimagen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`zonaimagen` ;

CREATE TABLE IF NOT EXISTS `gesane`.`zonaimagen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_imagen` INT NOT NULL,
  `id_zona` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_zonaimagen_imagen1_idx` (`id_imagen` ASC),
  INDEX `fk_zonaimagen_zona1_idx` (`id_zona` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`prioridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`prioridad` ;

CREATE TABLE IF NOT EXISTS `gesane`.`prioridad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`tipomuestra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`tipomuestra` ;

CREATE TABLE IF NOT EXISTS `gesane`.`tipomuestra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`anticoagulante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`anticoagulante` ;

CREATE TABLE IF NOT EXISTS `gesane`.`anticoagulante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`analitica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`analitica` ;

CREATE TABLE IF NOT EXISTS `gesane`.`analitica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `informe` LONGTEXT NULL,
  `fecha_peticion` DATETIME NULL,
  `importe` DOUBLE NULL,
  `id_prioridad` INT NOT NULL,
  `id_tipomuestra` INT NOT NULL,
  `id_anticoagulante` INT NOT NULL,
  `id_episodio` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_analitica_prioridad1_idx` (`id_prioridad` ASC),
  INDEX `fk_analitica_tipomuestra1_idx` (`id_tipomuestra` ASC),
  INDEX `fk_analitica_anticoagulante1_idx` (`id_anticoagulante` ASC),
  INDEX `fk_analitica_episodio1_idx` (`id_episodio` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`tipodiagnostico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`tipodiagnostico` ;

CREATE TABLE IF NOT EXISTS `gesane`.`tipodiagnostico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`diagnostico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`diagnostico` ;

CREATE TABLE IF NOT EXISTS `gesane`.`diagnostico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`poa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`poa` ;

CREATE TABLE IF NOT EXISTS `gesane`.`poa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`episodiodiagnostico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`episodiodiagnostico` ;

CREATE TABLE IF NOT EXISTS `gesane`.`episodiodiagnostico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `id_tipodiagnostico` INT NOT NULL,
  `id_episodio` INT NOT NULL,
  `id_diagnostico` INT NOT NULL,
  `id_poa` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_episodiodiagnostico_tipodiagnostico1_idx` (`id_tipodiagnostico` ASC),
  INDEX `fk_episodiodiagnostico_episodio1_idx` (`id_episodio` ASC),
  INDEX `fk_episodiodiagnostico_diagnostico1_idx` (`id_diagnostico` ASC),
  INDEX `fk_episodiodiagnostico_poa1_idx` (`id_poa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`instrumentalista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`instrumentalista` ;

CREATE TABLE IF NOT EXISTS `gesane`.`instrumentalista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `primer_apellido` VARCHAR(255) NULL,
  `segundo_apellido` VARCHAR(255) NULL,
  `dni` VARCHAR(255) NULL,
  `telefono` VARCHAR(255) NULL,
  `fecha_nacimiento` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `num_colegiado` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`tipoprocedimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`tipoprocedimiento` ;

CREATE TABLE IF NOT EXISTS `gesane`.`tipoprocedimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`procedimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`procedimiento` ;

CREATE TABLE IF NOT EXISTS `gesane`.`procedimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` LONGTEXT NULL,
  `id_tipoprocedimiento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_procedimiento_tipoprocedimiento1_idx` (`id_tipoprocedimiento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`episodioprocedimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gesane`.`episodioprocedimiento` ;

CREATE TABLE IF NOT EXISTS `gesane`.`episodioprocedimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  `id_instrumentalista` INT NULL,
  `id_episodio` INT NULL,
  `id_medico` INT NULL,
  `id_dependencia` INT NULL,
  `informe` LONGTEXT NULL,
  `diagnostico_inicial` LONGTEXT NULL,
  `diagnostico_final` LONGTEXT NULL,
  `procedimiento_previsto` LONGTEXT NULL,
  `procedimiento_realizado` LONGTEXT NULL,
  `id_prioridad` INT NOT NULL,
  `id_procedimiento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_episodioprocedimiento_instrumentalista1_idx` (`id_instrumentalista` ASC),
  INDEX `fk_episodioprocedimiento_episodio1_idx` (`id_episodio` ASC),
  INDEX `fk_episodioprocedimiento_medico1_idx` (`id_medico` ASC),
  INDEX `fk_episodioprocedimiento_dependencia1_idx` (`id_dependencia` ASC),
  INDEX `fk_procedimiento_prioridad1_idx` (`id_prioridad` ASC),
  INDEX `fk_procedimiento_procedimiento1_idx` (`id_procedimiento` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
