-- MySQL Script generated by MySQL Workbench
-- mar 12 dic 2017 08:26:38 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gesane
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gesane` ;

-- -----------------------------------------------------
-- Schema gesane
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gesane` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `gesane` ;

-- -----------------------------------------------------
-- Table `gesane`.`tiposervicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`tiposervicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`servicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `codigo` VARCHAR(255) NULL,
  `id_tiposervicio` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_servicio_tiposervicio_idx` (`id_tiposervicio` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`tipopago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`tipopago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`sexo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`tipousuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(255) NULL,
  `id_curso` INT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grupo_curso1_idx` (`id_curso` ASC),
  INDEX `fk_grupo_usuario1_idx` (`id_usuario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`centro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`centro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `codigo` VARCHAR(255) NULL,
  `poblacion` VARCHAR(255) NULL,
  `provincia` VARCHAR(255) NULL,
  `telefono` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `direccion` VARCHAR(255) NULL,
  `cod_postal` VARCHAR(255) NULL,
  `pais` VARCHAR(255) NULL,
  `publico` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`centrosanitario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`centrosanitario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `primer_apellido` VARCHAR(255) NULL,
  `segundo_apellido` VARCHAR(255) NULL,
  `login` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `token` VARCHAR(45) NULL,
  `activo` TINYINT(1) NULL,
  `fecha_alta` DATETIME NULL,
  `validado` TINYINT(1) NULL,
  `id_tipousuario` INT NULL,
  `id_grupo` INT NULL,
  `id_centro` INT NULL,
  `id_centrosanitario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tipousuario1_idx` (`id_tipousuario` ASC),
  INDEX `fk_usuario_grupo1_idx` (`id_grupo` ASC),
  INDEX `fk_usuario_centro1_idx` (`id_centro` ASC),
  INDEX `fk_usuario_centrosanitario1_idx` (`id_centrosanitario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(255) NULL,
  `nombre` VARCHAR(255) NULL,
  `primer_apellido` VARCHAR(255) NULL,
  `segundo_apellido` VARCHAR(255) NULL,
  `direccion` VARCHAR(255) NULL,
  `ciudad` VARCHAR(255) NULL,
  `codigo_postal` VARCHAR(255) NULL,
  `provincia` VARCHAR(255) NULL,
  `pais` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `telefono1` VARCHAR(45) NULL,
  `telefono2` VARCHAR(45) NULL,
  `nombre_padre` VARCHAR(255) NULL,
  `nombre_madre` VARCHAR(255) NULL,
  `fecha_nacimiento` DATETIME NULL,
  `ciudad_nacimiento` VARCHAR(255) NULL,
  `pais_nacimiento` VARCHAR(255) NULL,
  `sip_aseguradora` VARCHAR(45) NULL,
  `id_tipopago` INT NULL,
  `id_sexo` INT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_paciente_tipopago1_idx` (`id_tipopago` ASC),
  INDEX `fk_paciente_sexo1_idx` (`id_sexo` ASC),
  INDEX `fk_paciente_usuario1_idx` (`id_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`tipodependencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`tipodependencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`dependencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`dependencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  `id_tipodependencia` INT NULL,
  `id_centrosanitario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dependencia_tipodependencia1_idx` (`id_tipodependencia` ASC),
  INDEX `fk_dependencia_centrosanitario1_idx` (`id_centrosanitario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`especialidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`categoriaprofesional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`categoriaprofesional` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`medico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_servicio` INT NULL,
  `id_especialidad` INT NULL,
  `dni` VARCHAR(255) NULL,
  `nombre` VARCHAR(255) NULL,
  `primer_apellido` VARCHAR(255) NULL,
  `segundo_apellido` VARCHAR(255) NULL,
  `fecha_nacimiento` DATETIME NULL,
  `num_colegiado` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `id_categoriaprofesional` INT NULL,
  `id_centrosanitario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medico_servicio1_idx` (`id_servicio` ASC),
  INDEX `fk_medico_especialidad1_idx` (`id_especialidad` ASC),
  INDEX `fk_medico_categoriaprofesional1_idx` (`id_categoriaprofesional` ASC),
  INDEX `fk_medico_centrosanitario1_idx` (`id_centrosanitario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`tipoepisodio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`tipoepisodio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`circunstanciasalta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`circunstanciasalta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`destinoalta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`destinoalta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`modalidadepisodio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`modalidadepisodio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`episodio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`episodio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_firma` DATETIME NULL,
  `fecha_inicio` DATETIME NULL,
  `fecha_alta` DATETIME NULL,
  `importe` DOUBLE NULL,
  `finalizado` TINYINT(1) NULL,
  `bloqueado` TINYINT(1) NULL,
  `id_servicio` INT NULL,
  `id_paciente` INT NULL,
  `id_factura` INT NULL,
  `id_dependencia` INT NULL,
  `id_medico` INT NULL,
  `id_tipoepisodio` INT NULL,
  `id_episodio` INT NULL,
  `id_circunstanciasalta` INT NULL,
  `id_destinoalta` INT NULL,
  `id_modalidadepisodio` INT NULL,
  `id_usuario` INT NULL,
  `motivo_ingreso` LONGTEXT NULL,
  `antecedentes` LONGTEXT NULL,
  `historia_actual` LONGTEXT NULL,
  `exploracion_fisica` LONGTEXT NULL,
  `evolucion_comentarios` LONGTEXT NULL,
  `diagnostico_principal` LONGTEXT NULL,
  `diagnostico_secundarios` LONGTEXT NULL,
  `procedimientos` LONGTEXT NULL,
  `tratamiento_recomendaciones` LONGTEXT NULL,
  `tratamiento_farmacos` LONGTEXT NULL,
  `recomendaciones` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_episodio_servicio1_idx` (`id_servicio` ASC),
  INDEX `fk_episodio_paciente1_idx` (`id_paciente` ASC),
  INDEX `fk_episodio_factura1_idx` (`id_factura` ASC),
  INDEX `fk_episodio_dependencia1_idx` (`id_dependencia` ASC),
  INDEX `fk_episodio_medico1_idx` (`id_medico` ASC),
  INDEX `fk_episodio_tipoepisodio1_idx` (`id_tipoepisodio` ASC),
  INDEX `fk_episodio_episodio1_idx` (`id_episodio` ASC),
  INDEX `fk_episodio_circunstanciasalta1_idx` (`id_circunstanciasalta` ASC),
  INDEX `fk_episodio_destinoalta1_idx` (`id_destinoalta` ASC),
  INDEX `fk_episodio_modalidadepisodio1_idx` (`id_modalidadepisodio` ASC),
  INDEX `fk_episodio_usuario1_idx` (`id_usuario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`medicamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`via`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`via` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`posologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`posologia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`tratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`tratamiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  `cuidados` LONGTEXT NULL,
  `importe` DOUBLE NULL,
  `id_medicamento` INT NULL,
  `id_posologia` INT NULL,
  `id_via` INT NULL,
  `id_episodio` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tratamiento_medicamento1_idx` (`id_medicamento` ASC),
  INDEX `fk_tratamiento_posologia1_idx` (`id_posologia` ASC),
  INDEX `fk_tratamiento_via1_idx` (`id_via` ASC),
  INDEX `fk_tratamiento_episodio1_idx` (`id_episodio` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`prueba_informada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`prueba_informada` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `informe` LONGTEXT NULL,
  `fecha_peticion` DATETIME NULL,
  `importe` DOUBLE NULL,
  `id_episodio` INT NULL,
  `id_medico` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prueba_episodio1_idx` (`id_episodio` ASC),
  INDEX `fk_prueba_informada_medico1_idx` (`id_medico` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`catalogoimagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`catalogoimagenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `instrucciones` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`especialidad_tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`especialidad_tecnico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`tecnico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(255) NULL,
  `nombre` VARCHAR(255) NULL,
  `primer_apellido` VARCHAR(255) NULL,
  `segundo_apellido` VARCHAR(255) NULL,
  `fecha_nacimiento` DATETIME NULL,
  `num_tecnico` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `id_centrosanitario` INT NULL,
  `id_especialidad_tecnico` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medico_centrosanitario1_idx` (`id_centrosanitario` ASC),
  INDEX `fk_tecnico_especialidad_tecnico1_idx` (`id_especialidad_tecnico` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`imagen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `fecha_prevista` DATETIME NULL,
  `fecha_realizacion` DATETIME NULL,
  `ubicacion` VARCHAR(255) NULL,
  `id_catalogo` INT NULL,
  `id_prueba` INT NULL,
  `id_dependencia` INT NULL,
  `importe` DOUBLE NULL,
  `id_tecnico` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_imagen_catalogo1_idx` (`id_catalogo` ASC),
  INDEX `fk_imagen_prueba1_idx` (`id_prueba` ASC),
  INDEX `fk_imagen_dependencia1_idx` (`id_dependencia` ASC),
  INDEX `fk_imagen_tecnico1_idx` (`id_tecnico` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`tipodiagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`tipodiagnostico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`diagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`diagnostico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(255) NULL,
  `descripcion` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`poa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`poa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`episodiodiagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`episodiodiagnostico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `id_tipodiagnostico` INT NULL,
  `id_episodio` INT NULL,
  `id_diagnostico` INT NULL,
  `id_poa` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_episodiodiagnostico_tipodiagnostico1_idx` (`id_tipodiagnostico` ASC),
  INDEX `fk_episodiodiagnostico_episodio1_idx` (`id_episodio` ASC),
  INDEX `fk_episodiodiagnostico_diagnostico1_idx` (`id_diagnostico` ASC),
  INDEX `fk_episodiodiagnostico_poa1_idx` (`id_poa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`instrumentalista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`instrumentalista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `primer_apellido` VARCHAR(255) NULL,
  `segundo_apellido` VARCHAR(255) NULL,
  `dni` VARCHAR(255) NULL,
  `telefono` VARCHAR(255) NULL,
  `fecha_nacimiento` DATETIME NULL,
  `email` VARCHAR(255) NULL,
  `num_colegiado` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`prioridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`prioridad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`tipoprocedimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`tipoprocedimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`catalogoprocedimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`catalogoprocedimientos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(255) NULL,
  `descripcion` LONGTEXT NULL,
  `id_tipoprocedimiento` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_procedimiento_tipoprocedimiento1_idx` (`id_tipoprocedimiento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`procedimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`procedimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  `id_instrumentalista` INT NULL,
  `id_episodio` INT NULL,
  `id_medico` INT NULL,
  `id_dependencia` INT NULL,
  `informe` LONGTEXT NULL,
  `diagnostico_inicial` LONGTEXT NULL,
  `diagnostico_final` LONGTEXT NULL,
  `procedimiento_previsto` LONGTEXT NULL,
  `procedimiento_realizado` LONGTEXT NULL,
  `id_prioridad` INT NULL,
  `id_procedimiento` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_episodioprocedimiento_instrumentalista1_idx` (`id_instrumentalista` ASC),
  INDEX `fk_episodioprocedimiento_episodio1_idx` (`id_episodio` ASC),
  INDEX `fk_episodioprocedimiento_medico1_idx` (`id_medico` ASC),
  INDEX `fk_episodioprocedimiento_dependencia1_idx` (`id_dependencia` ASC),
  INDEX `fk_procedimiento_prioridad1_idx` (`id_prioridad` ASC),
  INDEX `fk_procedimiento_procedimiento1_idx` (`id_procedimiento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gesane`.`catalogoanaliticas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`catalogoanaliticas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `instrucciones` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gesane`.`analitica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gesane`.`analitica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `fecha_prevista` DATETIME NULL,
  `fecha_realizacion` DATETIME NULL,
  `ubicacion` VARCHAR(255) NULL,
  `id_medico` INT NULL,
  `id_dependencia` INT NULL,
  `id_catalogoanaliticas` INT NULL,
  `importe` DOUBLE NULL,
  `id_episodio` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_imagen_medico1_idx` (`id_medico` ASC),
  INDEX `fk_imagen_dependencia1_idx` (`id_dependencia` ASC),
  INDEX `fk_analitica_catalogoanaliticas1_idx` (`id_catalogoanaliticas` ASC),
  INDEX `fk_analitica_episodio1_idx` (`id_episodio` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `gesane`.`tiposervicio`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`tiposervicio` (`id`, `descripcion`) VALUES (1, 'urgencias');
INSERT INTO `gesane`.`tiposervicio` (`id`, `descripcion`) VALUES (2, 'cuidados intensivos');
INSERT INTO `gesane`.`tiposervicio` (`id`, `descripcion`) VALUES (3, 'hospitalización');
INSERT INTO `gesane`.`tiposervicio` (`id`, `descripcion`) VALUES (4, 'cuidados neonatológicos');
INSERT INTO `gesane`.`tiposervicio` (`id`, `descripcion`) VALUES (5, 'tratamiento del dolor');
INSERT INTO `gesane`.`tiposervicio` (`id`, `descripcion`) VALUES (6, 'emergencia');
INSERT INTO `gesane`.`tiposervicio` (`id`, `descripcion`) VALUES (7, 'laboratorio');
INSERT INTO `gesane`.`tiposervicio` (`id`, `descripcion`) VALUES (8, 'farmacia');
INSERT INTO `gesane`.`tiposervicio` (`id`, `descripcion`) VALUES (9, 'consultas externas');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`servicio`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (1, 'Anatomía', 'ANA', 1);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (2, 'Anestesiología y reanimación', 'ANE', 2);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (3, 'Cirugía general', 'CIR', 1);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (4, 'Medicina familiar', 'MFAM', 1);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (5, 'Medicina interna', 'MINT', 1);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (6, 'Neumología', 'NEUM', 1);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (7, 'Neurocirugía', 'NEURC', 1);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (8, 'Neurología', 'NEURL', 1);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (9, 'Obstetricia y ginecología.', 'GINE', 1);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (10, 'Oftalmología', 'OFT', 1);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (11, 'Otorrinolaringología', 'OTO', 1);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (12, 'Pediatría', 'PEDI', 1);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (13, 'Psiquiatría', 'PSI', 1);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (14, 'Traumatología', 'TRAUMA', 1);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (15, 'Urología', 'URO', 1);
INSERT INTO `gesane`.`servicio` (`id`, `descripcion`, `codigo`, `id_tiposervicio`) VALUES (16, 'Digestivo', 'DIGES', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`sexo`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`sexo` (`id`, `descripcion`) VALUES (1, 'Hombre');
INSERT INTO `gesane`.`sexo` (`id`, `descripcion`) VALUES (2, 'Mujer');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`tipousuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`tipousuario` (`id`, `descripcion`) VALUES (1, 'Administrador');
INSERT INTO `gesane`.`tipousuario` (`id`, `descripcion`) VALUES (2, 'Profesor organizador');
INSERT INTO `gesane`.`tipousuario` (`id`, `descripcion`) VALUES (3, 'Profesor');
INSERT INTO `gesane`.`tipousuario` (`id`, `descripcion`) VALUES (4, 'Alumno');
INSERT INTO `gesane`.`tipousuario` (`id`, `descripcion`) VALUES (5, 'Visitante');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`curso`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`curso` (`id`, `descripcion`) VALUES (1, '2016-2017');
INSERT INTO `gesane`.`curso` (`id`, `descripcion`) VALUES (2, '2017-2018');
INSERT INTO `gesane`.`curso` (`id`, `descripcion`) VALUES (3, '2018-2019');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`grupo`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`grupo` (`id`, `codigo`, `id_curso`, `id_usuario`) VALUES (1, 'ausias-mariajose-2016-2017', 1, 3);
INSERT INTO `gesane`.`grupo` (`id`, `codigo`, `id_curso`, `id_usuario`) VALUES (2, 'ausias-isabel-2016-2017', 1, 7);
INSERT INTO `gesane`.`grupo` (`id`, `codigo`, `id_curso`, `id_usuario`) VALUES (3, 'sagunto-maria-2016-2017', 1, 9);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`centro`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`centro` (`id`, `nombre`, `codigo`, `poblacion`, `provincia`, `telefono`, `email`, `direccion`, `cod_postal`, `pais`, `publico`) VALUES (1, 'CIPFP Ausiàs March', '46021711', 'Valencia', 'Valencia', '961205930', 'secretaria@ausiasmarch.net', 'C/Ángel de Villena, s/n.', '46013', 'España', 1);
INSERT INTO `gesane`.`centro` (`id`, `nombre`, `codigo`, `poblacion`, `provincia`, `telefono`, `email`, `direccion`, `cod_postal`, `pais`, `publico`) VALUES (2, 'IES JORGE JUAN', '46007554', 'Puerto de Sagunto', 'Valencia', '962617730', '46007554@gva.es', 'Avda. Fausto Caruana, s/n', '46520', 'España', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`centrosanitario`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`centrosanitario` (`id`, `descripcion`) VALUES (1, 'Centro Sanitario Ausiàs March');
INSERT INTO `gesane`.`centrosanitario` (`id`, `descripcion`) VALUES (2, 'Centro Sanitario Puerto de Sagunto');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (1, 'Rafael', 'Aznar', 'Aparici', 'rafael', '79063E8037FFF16D297A1FE65136F1251126CDDB2CC9870ECF8D653835538E85', 'rafaaznar@gmail.com', 'NULL', 1, '2017-05-22 00:00:00', 1, 1, 0, 1, 0);
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (2, 'Isabel', 'Gimeno', 'Soro', 'coordinadora', 'eb5094069f5e287ad7cfce5fc944f1c6565da2481af83fd5c24568e2481d09e3', 'isabel@ausias.net', 'NULL', 1, '2017-06-05 00:00:00', 1, 2, 0, 1, 0);
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (3, 'Maria José', 'García', 'García-Saavedra', 'mariajose', 'dd5b32c15fc56be8570bd485aa6baccd685384bd03c9fe947a510376cc4978a6', 'mgarcia@ausiasmarch.net', 'NULL', 1, '2017-06-05 00:00:00', 1, 3, 0, 1, 1);
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (4, 'Raquel', 'Gómez', 'Tortajada', 'raquel', '6e1f3da6cf8847b5c2ced23d0fa63272e6cd630dabe13b73f1d2666b0cb1444d', 'r@au.es', 'NULL', 1, '2017-06-05 00:00:00', 1, 4, 1, 1, 0);
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (5, 'Carlos', 'Ricart', 'Pérez', 'carlos', 'd066e50365a1d5f4028883c3e092a57d233e96b53aa3d48c172862d5b4c72670', 'segis@au.net', 'NULL', 1, '2017-06-04 00:00:00', 1, 4, 1, 1, 0);
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (6, 'Pepe', 'Minas', 'Plaza', 'pepe', '7c9e7c1494b2684ab7c19d6aff737e460fa9e98d5a234da1310c97ddf5691834', 'pepe@aus.net', 'NULL', 0, '2017-06-01 00:00:00', 1, 4, 1, 1, 0);
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (7, 'Isabel', 'Gimeno', 'Soro', 'isabel', 'EB5094069F5E287AD7CFCE5FC944F1C6565DA2481AF83FD5C24568E2481D09E3', 'isa@ausias.net', 'NULL', 1, '2017-06-04 00:00:00', 1, 3, 0, 1, 1);
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (8, 'Ana', 'García', 'Ridaura', 'ana', '24d4b96f58da6d4a8512313bbd02a28ebf0ca95dec6e4c86ef78ce7f01e788ac', 'ana@ass.es', 'NULL', 1, '2017-06-04 00:00:00', 1, 4, 2, 1, 0);
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (9, 'Maria', 'Cullell', 'García', 'maria', '94aec9fbed989ece189a7e172c9cf41669050495152bc4c1dbf2a38d7fd85627', 'm@mm.es', 'NULL', 1, 'NULL', 1, 3, 0, 2, 2);
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (10, 'Sergio', 'Faus', 'RodrÃ­guez', 'sergio', '36033babfb48ec64e197c97fb40d65e6c79f81e04c61aeccef3009e01645ab8d', 'sergio@sumail.com', 'NULL', 0, '2017-06-01 00:00:00', 1, 4, 2, 1, 0);
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (11, 'Sandra', 'López', 'Miranda', 'sandra', '83ed5207a41179600b50c409a460cfc229c60cb91bf06480d705c923c864e501', 'sandra@aus.es', 'NULL', 0, '2017-06-02 00:00:00', 1, 4, 3, 2, 0);
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (12, 'Eva', 'Tamarit', 'Ripoll', 'eva', '02b15ef87562676a8a42f33af9a0ca6aa11e491abda98cec24e4eded61ffa78d', 'eva@fkjd.es', 'NULL', 0, '2017-06-02 00:00:00', 1, 4, 3, 2, 0);
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (13, 'Der', 'Dsa', 'Drw', 'der', '03587D3A7482EE565DE65B99C0C0448F95B9253AD76C96CA5D0D198AD5E563A2', 'aitrelo@ono.com', '3bd1ae6f7cb6f2ccb209', 0, '2017-06-26 04:50:00', 0, 4, 1, 1, 1);
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (14, 'Aqw', 'Azx', 'Wer', 'aseee', '03587D3A7482EE565DE65B99C0C0448F95B9253AD76C96CA5D0D198AD5E563A2', 'ew@er.es', 'ce36f497cec05af3acfc', 0, '2017-06-26 11:02:00', 0, 4, 1, 1, 1);
INSERT INTO `gesane`.`usuario` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `login`, `password`, `email`, `token`, `activo`, `fecha_alta`, `validado`, `id_tipousuario`, `id_grupo`, `id_centro`, `id_centrosanitario`) VALUES (15, 'ewr', 'wer', 'fsdf', 'qwe', 'NULL', 'qqq@www.es', '321231', 1, '2017-07-03 00:00:00', 1, 1, 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`paciente`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (DEFAULT, '34523421J', 'Adela', 'Román', 'Segura', 'Alzira 26-4', 'Valencia', '46019', 'Valencia', 'España', 'adese@gesane.net', '543544534', '985453453', 'Roberto', 'María', '2001-03-03', 'Valencia', 'España', '434323423', 1, 2, 2);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '34523421J', 'Adela', 'Román', 'Segura', 'Alzira 26-4', 'Valencia', '46019', 'Valencia', 'España', 'adese@gesane.net', '543544534', '985453453', 'Roberto', 'María', '2001-03-03', 'Valencia', 'España', '434323423', 1, 2, 2);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '12345678A', 'Federico', 'Garcia', 'Lorca', 'Paterna 34-5', 'Valencia', '46003', 'Valencia', 'España', 'fedegarlo@gesane.net', '613246423', '961232343', 'Juan', 'Rigoberta', '1925-11-11', 'Valencia', 'España', '292292922', 1, 1, 1);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '23456789H', 'Filomena', 'Martinez', 'Guardiola', 'Mislata 15-6', 'Valencia', '45012', 'Valencia', 'España', 'filomagu@gesane.net', '625484582', '963578421', 'Marcos', 'Felipa', '1964-06-12', 'Valencia', 'España', '167251674', 2, 2, 3);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '26348723U', 'Teofila', 'Gimenez', 'Villalba', 'Valencia 25-5', 'Valencia', '46034', 'Valencia', 'España', 'teogivi@gesane.net', '641455544', '968722425', 'Julio', 'Dolores', '1978-08-07', 'Valencia', 'España', '846545345', 1, 2, 4);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '82713891D', 'Antonio', 'Sanchez', 'Fernandez', 'Carcaixent 12-4', 'Valencia', '44004', 'Valencia', 'España', 'ansanfer@gesane.net', '613285455', '957616765', 'Antonio', 'Rocio', '1964-09-09', 'Valencia', 'España', '846542121', 2, 1, 5);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '74298479I', 'Luis', 'Garcia', 'Izquierdo', 'Benetusser 2-1', 'Valencia', '41001', 'Valencia', 'España', 'lugariz@gesane.net', '678978878', '936751576', 'Luis', 'Maria Jesus', '1999-04-01', 'Valencia', 'España', '123843545', 2, 1, 2);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '18238183Z', 'Saray', 'Barneda', 'Pinto', 'Valencia 12-3', 'Valencia', '46022', 'Valencia', 'España', 'sabarpin@gesane.net', '447578867', '962579267', 'Alberto', 'Marina', '1996-02-29', 'Valencia', 'España', '435135485', 1, 2, 3);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '78492749K', 'Raquel', 'Izquierdo', 'Gutierrez', 'Valencia 15-2', 'Valencia', '46035', 'Valencia', 'España', 'raizgu@gesane.net', '791765646', '956731628', 'Ramon', 'Soledad', '1987-12-04', 'Valencia', 'España', '135432454', 1, 2, 4);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '29342984S', 'Carlos', 'Ahedo', 'Torti', 'Alzira 26-4', 'Valencia', '46019', 'Valencia', 'España', 'caraltor@gesane.net', '164326455', '976751682', 'Ismael', 'Sara', '1973-01-05', 'Valencia', 'España', '544543248', 2, 1, 1);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '74283422I', 'Cristina', 'Del Monte', 'Sanchez', 'Paterna 15-5', 'Valencia', '46012', 'Valencia', 'España', 'crismonsan@gesane.net', '465646572', '963461243', 'Diego', 'Maria', '1958-03-08', 'Valencia', 'España', '451321832', 1, 2, 4);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '19837813F', 'Oscar', 'Martinez', 'Tarradellas', 'Valencia 1-1', 'Valencia', '46001', 'Valencia', 'España', 'osmartar@gesane.net', '619792672', '964327527', 'Alvaro', 'Encarnacion', '1971-12-06', 'Valencia', 'España', '158315435', 2, 1, 3);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '32515251Q', 'Julian', 'Olmedo', 'Paredes', 'Alzira 12-7', 'Valencia', '46002', 'Valencia', 'España', 'juolpa@gesane.net', '648451887', '964817544', 'Arevalo', 'Josefina', '1988-10-14', 'Madrid', 'España', '534534633', 2, 1, 3);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '18726144P', 'Adrian', 'Scheidemann', 'Kast', 'Valencia 12-5', 'Valencia', '46022', 'Valencia', 'España', 'adshka@gesane.net', '645654455', '621488465', 'Nietzsche', 'Anna', '1997-11-29', 'Munich', 'Alemania', '234265723', 1, 1, 1);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '26381337G', 'Fernando', 'Molina', 'Gutierrez', 'Valencia 22-2', 'Valencia', '46012', 'Valencia', 'España', 'fermolgu@gesane.net', '641975175', '964542465', 'Jose', 'Matilda', '1950-06-04', 'Paris', 'Francia', '734534523', 2, 1, 4);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '67386482K', 'Alberto', 'Contreras', 'Espinosa', 'Paterna 1-5', 'Valencia', '46018', 'Valencia', 'España', 'alcones@gesane.net', '126721372', '964546456', 'Marcos', 'Ana', '1978-03-17', 'Castellon', 'España', '234623234', 1, 1, 5);
INSERT INTO `gesane`.`paciente` (`id`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `direccion`, `ciudad`, `codigo_postal`, `provincia`, `pais`, `email`, `telefono1`, `telefono2`, `nombre_padre`, `nombre_madre`, `fecha_nacimiento`, `ciudad_nacimiento`, `pais_nacimiento`, `sip_aseguradora`, `id_tipopago`, `id_sexo`, `id_usuario`) VALUES (NULL, '72634827Y', 'Pablo', 'Carretas', 'Domingo', 'Valencia 13-5', 'Valencia', '46097', 'Valencia', 'España', 'pacardo@gesane.net', '465121561', '964874545', 'Rafael', 'Sofia', '1968-05-04', 'Bilbao', 'España', '262342623', 2, 1, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`factura`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`factura` (`id`, `descripcion`, `fecha`) VALUES (1, 'A7676876', '2010-10-05');
INSERT INTO `gesane`.`factura` (`id`, `descripcion`, `fecha`) VALUES (2, 'S4344434', '2010-10-05');
INSERT INTO `gesane`.`factura` (`id`, `descripcion`, `fecha`) VALUES (3, 'W5345545', '2010-10-05');
INSERT INTO `gesane`.`factura` (`id`, `descripcion`, `fecha`) VALUES (4, 'T5454545', '2010-10-05');
INSERT INTO `gesane`.`factura` (`id`, `descripcion`, `fecha`) VALUES (5, 'E4344343', '2010-10-05');
INSERT INTO `gesane`.`factura` (`id`, `descripcion`, `fecha`) VALUES (6, 'E4333345', '2010-10-05');
INSERT INTO `gesane`.`factura` (`id`, `descripcion`, `fecha`) VALUES (7, 'R4343434', '2010-10-05');
INSERT INTO `gesane`.`factura` (`id`, `descripcion`, `fecha`) VALUES (8, 'E3422222', '2010-10-05');
INSERT INTO `gesane`.`factura` (`id`, `descripcion`, `fecha`) VALUES (DEFAULT, 'Q1222145', '2010-10-05');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`tipodependencia`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`tipodependencia` (`id`, `descripcion`) VALUES (1, 'Quirofano');
INSERT INTO `gesane`.`tipodependencia` (`id`, `descripcion`) VALUES (2, 'Box de Urgencias');
INSERT INTO `gesane`.`tipodependencia` (`id`, `descripcion`) VALUES (3, 'Habitación ingreso');
INSERT INTO `gesane`.`tipodependencia` (`id`, `descripcion`) VALUES (4, 'UVI');
INSERT INTO `gesane`.`tipodependencia` (`id`, `descripcion`) VALUES (5, 'UCI');
INSERT INTO `gesane`.`tipodependencia` (`id`, `descripcion`) VALUES (6, 'Medicina Nuclear');
INSERT INTO `gesane`.`tipodependencia` (`id`, `descripcion`) VALUES (7, 'Resonancia Magnetica');
INSERT INTO `gesane`.`tipodependencia` (`id`, `descripcion`) VALUES (8, 'Rayos X');
INSERT INTO `gesane`.`tipodependencia` (`id`, `descripcion`) VALUES (9, 'Sala de Curas');
INSERT INTO `gesane`.`tipodependencia` (`id`, `descripcion`) VALUES (10, 'Enfermeria');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`dependencia`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (1, 'QIR1', 'Quirófano intervención rápida 1', 1, 1);
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (2, 'QIR2', 'Quirófano intervención rápida 1', 1, 1);
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (3, 'H101', 'Habitación 101', 3, 1);
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (4, 'H102', 'Habitación 102', 3, 1);
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (5, 'BX01', 'Box 1', 2, 1);
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (6, 'BX02', 'Box 2', 2, 1);
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (7, 'RX01', 'Rayos 1', 8, 1);
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (8, 'RX02', 'Rayos 2', 8, 1);
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (9, 'MN01', 'Medicina Nuclear 1', 6, 1);
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (10, 'MN02', 'Medicina Nuclear 2', 6, 1);
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (11, 'RM01', 'Resonancia Magnética 1', 7, 1);
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (12, 'RM02', 'Resonancia Magnética 2', 7, 1);
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (13, 'UCI1', 'Unidad Cuidados Intensivos 1', 5, 1);
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (14, 'UCI2', 'Unidad Cuidados Intensivos 2', 5, 1);
INSERT INTO `gesane`.`dependencia` (`id`, `codigo`, `descripcion`, `id_tipodependencia`, `id_centrosanitario`) VALUES (15, 'UVI1', 'Unidad Vigilancia Intensiva 1', 4, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`especialidad`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (1, 'Anatomía patológica');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (2, 'Anestesiología y reanimación.');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (3, 'Cirugía general y del aparato digestivo.');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (4, 'Medicina familiar y comunitaria.');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (5, 'Medicina interna.');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (6, 'Neumología');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (7, 'Neurocirugía');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (8, 'Neurología');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (9, 'Obstetricia y ginecología.');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (10, 'Oftalmología');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (11, 'Otorrinolaringología');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (12, 'Pediatría');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (13, 'Psiquiatría');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (14, 'Traumatología');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (15, 'Urología');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (16, 'Alergóloga');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (17, 'Inmunología');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (18, 'Nefrología');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (19, 'Neurofisiología');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (20, 'Reumatología');
INSERT INTO `gesane`.`especialidad` (`id`, `descripcion`) VALUES (21, 'Microbiología');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`categoriaprofesional`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`categoriaprofesional` (`id`, `descripcion`) VALUES (1, 'Médico residente');
INSERT INTO `gesane`.`categoriaprofesional` (`id`, `descripcion`) VALUES (2, 'Titular');
INSERT INTO `gesane`.`categoriaprofesional` (`id`, `descripcion`) VALUES (3, 'Jefe de servicio');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`medico`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (1, 1, 1, '78978765A', 'Antonio', 'García', 'Pérez', '1971-11-01 00:00:00', '12233', 'jose@med.es', 1, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (2, 1, 1, '92938475E', 'Miguel', 'Romero', 'Cantera', '1967-07-13 00:00:00', '44555', 'miroca@med.es', 1, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (3, 1, 2, '92938476Q', 'Antonia', 'Morcillo', 'Luengo', '1966-07-03 00:00:00', '33445', 'amorcillo@med.es', 2, 2);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (4, 2, 3, '92883615W', 'Felisa', 'Cordero', 'Indalecio', '1975-07-03 00:00:00', '22556', 'infeco@med.es', 2, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (5, 1, 1, '93887251F', 'Amado', 'Mador', 'Domo', '1978-07-28 00:00:00', '42342', 'amadormo@med.es', 2, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (6, 1, 2, '45468784K', 'Gonzalo', 'Mauricio', 'Gómez', '1985-07-20 00:00:00', '33356', 'goma@med.es', 2, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (7, 1, 2, '98745412H', 'Antonio', 'Ginés', 'Sancho', '1987-07-19 00:00:00', '4234', 'angina@med.es', 2, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (8, 1, 5, '54345567U', 'Roberta', 'Rubio', 'Sánchez', '1968-07-04 00:00:00', '42342', 'rorusa@med.es', 1, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (9, 1, 2, '29384653P', 'Milagros', 'Belenguer', 'García', '1970-07-19 00:00:00', '56465', 'gabe@med.es', 2, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (10, 1, 9, '11123094L', 'Diana', 'Barrachina', 'López', '1977-07-26 00:00:00', '42342', 'balo@med.es', 1, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (11, 2, 1, '35344533N', 'Salomé', 'Gómez', 'Aguirre', '1976-07-29 00:00:00', '86767', 'sagorre@med.es', 2, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (12, 2, 11, '65445948A', 'Pau', 'Serrano', 'Ponce', '1963-07-06 00:00:00', '23366', 'vizu@med.es', 1, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (13, 1, 2, '10023870U', 'Alberto', 'Artal', 'Sierra', '1968-07-03 00:00:00', '42344', 'alsi@med.es', 1, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (14, 1, 1, '02342456V', 'Victoria', 'Zúñica', 'Manrique', '1977-07-31 00:00:00', '3123', 'vicman@med.es', 1, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (15, 1, 2, '35345331A', 'Andrea', 'Balaguer', 'Gimeno', '1975-07-28 00:00:00', '53453', 'angiba@med.es', 1, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (16, 1, 3, '54399110S', 'Isabel', 'Girona', 'Bolinches', '1966-07-11 00:00:00', '2435', 'isabo@med.es', 1, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (17, 1, 4, '10029901C', 'Ana', 'Tárrega', 'López', '1985-07-26 00:00:00', '42369', 'anlota@med.es', 1, 1);
INSERT INTO `gesane`.`medico` (`id`, `id_servicio`, `id_especialidad`, `dni`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `num_colegiado`, `email`, `id_categoriaprofesional`, `id_centrosanitario`) VALUES (18, 1, 1, '90992876G', 'María', 'Silvestre', 'Agramunt', '1983-07-31 00:00:00', '4234', 'masia@med.es', 1, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`circunstanciasalta`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`circunstanciasalta` (`id`, `descripcion`) VALUES (1, 'Alta por curacion');
INSERT INTO `gesane`.`circunstanciasalta` (`id`, `descripcion`) VALUES (2, 'Alta por translado');
INSERT INTO `gesane`.`circunstanciasalta` (`id`, `descripcion`) VALUES (3, 'Alta voluntaria');
INSERT INTO `gesane`.`circunstanciasalta` (`id`, `descripcion`) VALUES (4, 'Alta por mejora');
INSERT INTO `gesane`.`circunstanciasalta` (`id`, `descripcion`) VALUES (5, 'Alta por fuga');
INSERT INTO `gesane`.`circunstanciasalta` (`id`, `descripcion`) VALUES (6, 'Alta por defuncion');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`destinoalta`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`destinoalta` (`id`, `descripcion`) VALUES (1, 'Domicilio');
INSERT INTO `gesane`.`destinoalta` (`id`, `descripcion`) VALUES (2, 'UTI');
INSERT INTO `gesane`.`destinoalta` (`id`, `descripcion`) VALUES (3, 'Unidad intermediaria');
INSERT INTO `gesane`.`destinoalta` (`id`, `descripcion`) VALUES (4, 'Unidad de internación');
INSERT INTO `gesane`.`destinoalta` (`id`, `descripcion`) VALUES (5, 'NAS');
INSERT INTO `gesane`.`destinoalta` (`id`, `descripcion`) VALUES (6, 'LODS');
INSERT INTO `gesane`.`destinoalta` (`id`, `descripcion`) VALUES (7, 'SAPSII');
INSERT INTO `gesane`.`destinoalta` (`id`, `descripcion`) VALUES (8, 'Residencia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`modalidadepisodio`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`modalidadepisodio` (`id`, `descripcion`) VALUES (1, 'Modalidad de Espisodio 1');
INSERT INTO `gesane`.`modalidadepisodio` (`id`, `descripcion`) VALUES (2, 'Modalidad de Espisodio 2');
INSERT INTO `gesane`.`modalidadepisodio` (`id`, `descripcion`) VALUES (3, 'Modalidad de Espisodio 3');
INSERT INTO `gesane`.`modalidadepisodio` (`id`, `descripcion`) VALUES (4, 'Modalidad de Espisodio 4');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`episodio`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`episodio` (`id`, `fecha_firma`, `fecha_inicio`, `fecha_alta`, `importe`, `finalizado`, `bloqueado`, `id_servicio`, `id_paciente`, `id_factura`, `id_dependencia`, `id_medico`, `id_tipoepisodio`, `id_episodio`, `id_circunstanciasalta`, `id_destinoalta`, `id_modalidadepisodio`, `id_usuario`, `motivo_ingreso`, `antecedentes`, `historia_actual`, `exploracion_fisica`, `evolucion_comentarios`, `diagnostico_principal`, `diagnostico_secundarios`, `procedimientos`, `tratamiento_recomendaciones`, `tratamiento_farmacos`, `recomendaciones`) VALUES (1, '2015-05-09', '2010-10-05', '2015-05-10', 98.75, true, false, 1, 2, 1, 2, 5, 1, 2, 3, 1, 1, 2, 'Fractura', 'Ninguno', 'Pronósitco a determinar', 'Si', 'Por determinar', 'Fractura del escafoides', 'Nada', 'Escayolar', 'Reposo y pastillas', 'Antiinflamatorios', 'Reposo');
INSERT INTO `gesane`.`episodio` (`id`, `fecha_firma`, `fecha_inicio`, `fecha_alta`, `importe`, `finalizado`, `bloqueado`, `id_servicio`, `id_paciente`, `id_factura`, `id_dependencia`, `id_medico`, `id_tipoepisodio`, `id_episodio`, `id_circunstanciasalta`, `id_destinoalta`, `id_modalidadepisodio`, `id_usuario`, `motivo_ingreso`, `antecedentes`, `historia_actual`, `exploracion_fisica`, `evolucion_comentarios`, `diagnostico_principal`, `diagnostico_secundarios`, `procedimientos`, `tratamiento_recomendaciones`, `tratamiento_farmacos`, `recomendaciones`) VALUES (2, '2014-06-04', '2005-11-21', '2014-06-05', 1176.3, true, false, 2, 1, 2, 1, 3, 1, 2, 2, 1, 2, 1, 'Fractura', 'Alergias severas', 'Pronósitco a determinar', 'Si', 'Por determinar', 'Fractura de la pelvis', 'Nada', 'Escayolar', 'Reposo y pastillas', 'Antiinflamatorios', 'Reposo');
INSERT INTO `gesane`.`episodio` (`id`, `fecha_firma`, `fecha_inicio`, `fecha_alta`, `importe`, `finalizado`, `bloqueado`, `id_servicio`, `id_paciente`, `id_factura`, `id_dependencia`, `id_medico`, `id_tipoepisodio`, `id_episodio`, `id_circunstanciasalta`, `id_destinoalta`, `id_modalidadepisodio`, `id_usuario`, `motivo_ingreso`, `antecedentes`, `historia_actual`, `exploracion_fisica`, `evolucion_comentarios`, `diagnostico_principal`, `diagnostico_secundarios`, `procedimientos`, `tratamiento_recomendaciones`, `tratamiento_farmacos`, `recomendaciones`) VALUES (3, '2009-02-12', '2000-02-20', '2009-02-13', 4728.43, true, false, 2, 3, 2, 3, 1, 2, 4, 3, 2, 1, 2, 'Fractura', 'Alergias severas', 'Pronósitco a determinar', 'No', 'Por determinar', 'Fractura del antebrazo izquierdo', 'Nada', 'Escayolar', 'Reposo y pastillas', 'Antiinflamatorios', 'Reposo');
INSERT INTO `gesane`.`episodio` (`id`, `fecha_firma`, `fecha_inicio`, `fecha_alta`, `importe`, `finalizado`, `bloqueado`, `id_servicio`, `id_paciente`, `id_factura`, `id_dependencia`, `id_medico`, `id_tipoepisodio`, `id_episodio`, `id_circunstanciasalta`, `id_destinoalta`, `id_modalidadepisodio`, `id_usuario`, `motivo_ingreso`, `antecedentes`, `historia_actual`, `exploracion_fisica`, `evolucion_comentarios`, `diagnostico_principal`, `diagnostico_secundarios`, `procedimientos`, `tratamiento_recomendaciones`, `tratamiento_farmacos`, `recomendaciones`) VALUES (4, '2017-12-11', '2017-11-11', '2004-08-22', 23.54, true, false, 1, 2, 3, 2, 1, 2, 1, 3, 2, 1, 1, 'Fractura', 'Ninguno', 'Pronósitco a determinar', 'No', 'Por determinar', 'Fractura de la rodilla iquierda', 'Nada', 'Escayolar', 'Reposo y pastillas', 'Antiinflamatorios', 'Reposo');
INSERT INTO `gesane`.`episodio` (`id`, `fecha_firma`, `fecha_inicio`, `fecha_alta`, `importe`, `finalizado`, `bloqueado`, `id_servicio`, `id_paciente`, `id_factura`, `id_dependencia`, `id_medico`, `id_tipoepisodio`, `id_episodio`, `id_circunstanciasalta`, `id_destinoalta`, `id_modalidadepisodio`, `id_usuario`, `motivo_ingreso`, `antecedentes`, `historia_actual`, `exploracion_fisica`, `evolucion_comentarios`, `diagnostico_principal`, `diagnostico_secundarios`, `procedimientos`, `tratamiento_recomendaciones`, `tratamiento_farmacos`, `recomendaciones`) VALUES (5, '2015-06-04', '2014-06-04', '1994-11-02', 199.75, true, false, 2, 1, 2, 1, 2, 3, 3, 2, 1, 1, 2, 'Fractura', 'Cirugía cervical', 'Pronósitco a determinar', 'Si', 'Por determinar', 'Fractura del escafoides', 'Nada', 'Escayolar', 'Reposo y pastillas', 'Antiinflamatorios', 'Reposo');
INSERT INTO `gesane`.`episodio` (`id`, `fecha_firma`, `fecha_inicio`, `fecha_alta`, `importe`, `finalizado`, `bloqueado`, `id_servicio`, `id_paciente`, `id_factura`, `id_dependencia`, `id_medico`, `id_tipoepisodio`, `id_episodio`, `id_circunstanciasalta`, `id_destinoalta`, `id_modalidadepisodio`, `id_usuario`, `motivo_ingreso`, `antecedentes`, `historia_actual`, `exploracion_fisica`, `evolucion_comentarios`, `diagnostico_principal`, `diagnostico_secundarios`, `procedimientos`, `tratamiento_recomendaciones`, `tratamiento_farmacos`, `recomendaciones`) VALUES (6, '2014-05-07', '2014-05-06', '2014-05-07', 5.43, true, false, 2, 1, 1, 3, 2, 3, 4, 3, 2, 1, 2, 'Fractura', 'Alergias severas', 'Pronósitco a determinar', 'No', 'Por determinar', 'Fractura de la rodilla iquierda', 'Reacción alégrica a la cortisona', 'Escayolar', 'Reposo y pastillas', 'Antiinflamatorios', 'Reposo');
INSERT INTO `gesane`.`episodio` (`id`, `fecha_firma`, `fecha_inicio`, `fecha_alta`, `importe`, `finalizado`, `bloqueado`, `id_servicio`, `id_paciente`, `id_factura`, `id_dependencia`, `id_medico`, `id_tipoepisodio`, `id_episodio`, `id_circunstanciasalta`, `id_destinoalta`, `id_modalidadepisodio`, `id_usuario`, `motivo_ingreso`, `antecedentes`, `historia_actual`, `exploracion_fisica`, `evolucion_comentarios`, `diagnostico_principal`, `diagnostico_secundarios`, `procedimientos`, `tratamiento_recomendaciones`, `tratamiento_farmacos`, `recomendaciones`) VALUES (7, '2016-03-09', '2016-01-01', '2016-03-10', 234.56, true, false, 3, 3, 2, 3, 3, 3, 2, 1, 1, 2, 3, 'Fractura', 'Cirugía cervical', 'Pronósitco a determinar', 'Si', 'Por determinar', 'Fractura inguinal', 'Nada', 'Escayolar', 'Reposo y pastillas', 'Antiinflamatorios', 'Reposo');
INSERT INTO `gesane`.`episodio` (`id`, `fecha_firma`, `fecha_inicio`, `fecha_alta`, `importe`, `finalizado`, `bloqueado`, `id_servicio`, `id_paciente`, `id_factura`, `id_dependencia`, `id_medico`, `id_tipoepisodio`, `id_episodio`, `id_circunstanciasalta`, `id_destinoalta`, `id_modalidadepisodio`, `id_usuario`, `motivo_ingreso`, `antecedentes`, `historia_actual`, `exploracion_fisica`, `evolucion_comentarios`, `diagnostico_principal`, `diagnostico_secundarios`, `procedimientos`, `tratamiento_recomendaciones`, `tratamiento_farmacos`, `recomendaciones`) VALUES (8, '2011-08-04', '2011-08-04', '2017-09-04', 2389.42, true, false, 5, 3, 4, 5, 4, 3, 4, 3, 2, 1, 3, 'Fractura', 'Ninguno', 'Pronósitco a determinar', 'No', 'Por determinar', 'Fractura de la rodilla iquierda', 'Nada', 'Escayolar', 'Reposo y pastillas', 'Antiinflamatorios', 'Reposo');
INSERT INTO `gesane`.`episodio` (`id`, `fecha_firma`, `fecha_inicio`, `fecha_alta`, `importe`, `finalizado`, `bloqueado`, `id_servicio`, `id_paciente`, `id_factura`, `id_dependencia`, `id_medico`, `id_tipoepisodio`, `id_episodio`, `id_circunstanciasalta`, `id_destinoalta`, `id_modalidadepisodio`, `id_usuario`, `motivo_ingreso`, `antecedentes`, `historia_actual`, `exploracion_fisica`, `evolucion_comentarios`, `diagnostico_principal`, `diagnostico_secundarios`, `procedimientos`, `tratamiento_recomendaciones`, `tratamiento_farmacos`, `recomendaciones`) VALUES (9, '2012-06-25', '2012-06-25', '2015-07-09', 312.35, true, false, 4, 5, 6, 3, 4, 5, 6, 4, 5, 4, 3, 'Fractura', 'Cirugía cervical', 'Pronósitco a determinar', 'No', 'Por determinar', 'Fractura de la rodilla iquierda', 'Nada', 'Escayolar', 'Reposo y pastillas', 'Antiinflamatorios', 'Reposo');
INSERT INTO `gesane`.`episodio` (`id`, `fecha_firma`, `fecha_inicio`, `fecha_alta`, `importe`, `finalizado`, `bloqueado`, `id_servicio`, `id_paciente`, `id_factura`, `id_dependencia`, `id_medico`, `id_tipoepisodio`, `id_episodio`, `id_circunstanciasalta`, `id_destinoalta`, `id_modalidadepisodio`, `id_usuario`, `motivo_ingreso`, `antecedentes`, `historia_actual`, `exploracion_fisica`, `evolucion_comentarios`, `diagnostico_principal`, `diagnostico_secundarios`, `procedimientos`, `tratamiento_recomendaciones`, `tratamiento_farmacos`, `recomendaciones`) VALUES (10, '2017-11-25', '2017-11-25', '2017-12-05', 49.95, true, false, 1, 2, 3, 4, 5, 6, 3, 4, 2, 1, 2, 'Fractura', 'Alergias severas', 'Pronósitco a determinar', 'Si', 'Por determinar', 'Fractura inguinal', 'Nada', 'Escayolar', 'Reposo y pastillas', 'Antiinflamatorios', 'Reposo');
INSERT INTO `gesane`.`episodio` (`id`, `fecha_firma`, `fecha_inicio`, `fecha_alta`, `importe`, `finalizado`, `bloqueado`, `id_servicio`, `id_paciente`, `id_factura`, `id_dependencia`, `id_medico`, `id_tipoepisodio`, `id_episodio`, `id_circunstanciasalta`, `id_destinoalta`, `id_modalidadepisodio`, `id_usuario`, `motivo_ingreso`, `antecedentes`, `historia_actual`, `exploracion_fisica`, `evolucion_comentarios`, `diagnostico_principal`, `diagnostico_secundarios`, `procedimientos`, `tratamiento_recomendaciones`, `tratamiento_farmacos`, `recomendaciones`) VALUES (11, '1994-09-20', '1994-11-25', '1995-01-03', 241.20, true, false, 3, 4, 5, 3, 2, 1, 2, 3, 4, 5, 6, 'Fractura', 'Alergias severas', 'Pronósitco a determinar', 'Si', 'Por determinar', 'Fractura de la rodilla iquierda', 'Alergia severa a los medicamentos en general', 'Escayolar', 'Reposo y caldo', 'Nada', 'Reposo');
INSERT INTO `gesane`.`episodio` (`id`, `fecha_firma`, `fecha_inicio`, `fecha_alta`, `importe`, `finalizado`, `bloqueado`, `id_servicio`, `id_paciente`, `id_factura`, `id_dependencia`, `id_medico`, `id_tipoepisodio`, `id_episodio`, `id_circunstanciasalta`, `id_destinoalta`, `id_modalidadepisodio`, `id_usuario`, `motivo_ingreso`, `antecedentes`, `historia_actual`, `exploracion_fisica`, `evolucion_comentarios`, `diagnostico_principal`, `diagnostico_secundarios`, `procedimientos`, `tratamiento_recomendaciones`, `tratamiento_farmacos`, `recomendaciones`) VALUES (12, '2008-03-14', '2008-03-15', '2008-04-24', 139.75, true, false, 3, 4, 5, 6, 4, 3, 2, 4, 5, 6, 4, 'Fractura', 'Ninguno', 'Pronósitco a determinar', 'Si', 'Por determinar', 'Fractura de la pelvis', 'Nada', 'Escayolar', 'Reposo y pastillas', 'Antiinflamatorios', 'Reposo');
INSERT INTO `gesane`.`episodio` (`id`, `fecha_firma`, `fecha_inicio`, `fecha_alta`, `importe`, `finalizado`, `bloqueado`, `id_servicio`, `id_paciente`, `id_factura`, `id_dependencia`, `id_medico`, `id_tipoepisodio`, `id_episodio`, `id_circunstanciasalta`, `id_destinoalta`, `id_modalidadepisodio`, `id_usuario`, `motivo_ingreso`, `antecedentes`, `historia_actual`, `exploracion_fisica`, `evolucion_comentarios`, `diagnostico_principal`, `diagnostico_secundarios`, `procedimientos`, `tratamiento_recomendaciones`, `tratamiento_farmacos`, `recomendaciones`) VALUES (13, '1998-06-24', '1998-06-24', '1998-06-30', 34.55, true, false, 1, 2, 3, 4, 5, 3, 2, 1, 2, 3, 1, 'Fractura', 'Ninguno', 'Pronósitco a determinar', 'No', 'Por determinar', 'Fractura del escafoides', 'Nada', 'Escayolar', 'Reposo y pastillas', 'Antiinflamatorios', 'Reposo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`medicamento`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (1, 'acetadote');
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (2, 'tylenol');
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (3, 'dulcolax');
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (4, 'hibiclens');
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (5, 'valium');
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (6, 'teveten');
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (7, 'motrin');
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (8, 'vicodin');
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (9, 'neurontin');
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (10, 'antizol');
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (11, 'isuprel');
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (12, 'mutamycin');
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (13, 'levatol');
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (14, 'trental');
INSERT INTO `gesane`.`medicamento` (`id`, `descripcion`) VALUES (15, 'astudal');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gesane`.`tipodiagnostico`
-- -----------------------------------------------------
START TRANSACTION;
USE `gesane`;
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (1, 'real');
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (2, 'de riesgo');
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (3, 'posible');
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (4, 'de síndrome');
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (5, 'diferencial');
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (6, 'genérico');
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (7, 'nosológico');
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (8, 'patogenético');
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (9, 'presuntivo');
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (10, 'sindrómico');
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (11, 'sintomático');
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (12, 'cierto');
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (13, 'clínico');
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (14, 'etiológico');
INSERT INTO `gesane`.`tipodiagnostico` (`id`, `descripcion`) VALUES (15, 'anatómico');

COMMIT;

